server:
  port: 8080
  tomcat:
    basedir: E:\TomcatTemp
spring:
  profiles:
    active: fzy
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

---
tree:
  db-path: E:\GitHub\PriTLD\PriTLD\DataBase
  data-path: E:\GitHub\PriTLD\Data
  temp-path: E:\GitHub\PriTLD\PriTLD\temp
spring:
  config:
    activate:
      on-profile: fzy
---
tree:
  db-path:
  data-path:
spring:
  config:
    activate:
      on-profile: lpz